[tool.poetry]
name = "course-project-bd"
version = "0.1.0"
description = ""
authors = ["Dmitriy Leonov <dmitriy.leonov.1993@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
